# Generated by Django 5.1.6 on 2025-03-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.URLField(default='https://elledecor.in/wp-content/uploads/2023/12/H1_Swwing.jpg'),
        ),
    ]
