# Generated by Django 5.1.6 on 2025-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_menu_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.URLField(default='https://d3sftlgbtusmnv.cloudfront.net/blog/wp-content/uploads/2025/01/Best-Food-In-Ooty-Cover-Photo-840x425.jpg'),
        ),
    ]
